### ISSUE TITLE
Roll into drupal package?

### ISSUE THREAD

**Issue by michaelfavia** [robballou/drupal-info-file#1]
Id be happy to make you a comaintainer on the drupal package unless you see a reason to have both.

**Comment by robballou** [comment]
@michaelfavia we can definitely roll this into the Drupal package. I think in the end it makes the most sense! Let me know how you want to handle that and I can help out.

**Comment by robballou** [comment]
This has been rolled into atom-drupal (finally) :+1:

That can probably use a new version when time allows

**Comment by michaelfavia** [comment]
Would you prefer to roll it or would you like me to?

**Comment by robballou** [comment]
I wasn't sure if I can apm publish for atom-drupal or not :)
